In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
df = pd.read_csv('/content/Fish.csv')

In [4]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [7]:
X = df.drop(['Length2','Length3','Species'] , axis = 1)
y = df['Species']

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25,stratify=y,random_state=100)

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

model_pipeline = Pipeline([
                  ('Scaler',StandardScaler()),
                  ('SVM',SVC())])

In [10]:
from sklearn.metrics import classification_report, confusion_matrix  
model_pipeline.fit(x_train,y_train)
predict = model_pipeline.predict(x_test)
print('\nEstimator: SVM') 
print(confusion_matrix(y_test,predict))  
print(classification_report(y_test,predict))  


Estimator: SVM
[[ 9  0  0  0  0  0  0]
 [ 1  2  0  0  0  0  0]
 [ 0  0 13  0  0  1  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  5  0  0  0  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  1  0  0  0  0]]
              precision    recall  f1-score   support

       Bream       0.90      1.00      0.95         9
      Parkki       1.00      0.67      0.80         3
       Perch       0.68      0.93      0.79        14
        Pike       1.00      1.00      1.00         4
       Roach       0.00      0.00      0.00         5
       Smelt       0.80      1.00      0.89         4
   Whitefish       0.00      0.00      0.00         1

    accuracy                           0.80        40
   macro avg       0.63      0.66      0.63        40
weighted avg       0.70      0.80      0.74        40



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
import pickle
pickle.dump(model_pipeline,open('regressor.pkl','wb'))